blog/src/Entity/Articles.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticlesRepository")
 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

blog/src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('author', TextType::class, ['label' => 'Никнейм'])
            ->add('title', TextType::class, ['label' => 'Заголовок'])
            ->add('content', TextareaType::class, ['label' => 'Текст статьи'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

blog/src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\Comments;
use App\Form\ArticlesType;
use App\Form\CommentsType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticlesController extends AbstractController
{
    /**
     * @Route("/", name="articles")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $articles = $em->getRepository(Articles::class)->findAll();
        return $this->render('articles/index.html.twig', [
            'controller_name' => 'ArticlesController',
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/single/{article}", name="single_article")
     */
    public function single(Articles $article)
    {
        $em = $this->getDoctrine()->getManager();
        $comments = $em->getRepository(Comments::class)->findBy(array('article_id' => $article->getId()),['id' => 'DESC'],10);
        return $this->render('articles/single.html.twig', [
            'articles' => $article,
            'comments' => $comments,
        ]);
    }

    /**
     * @Route("/create", name="create_article")
     */
    public function create(Request $request)
    {
        $article = new Articles();

        $form = $this->createForm(ArticlesType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $article = $form->getData();
            $article->setCreatedAt(new \DateTime('now'));

            $em = $this->getDoctrine()->getManager();

            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('articles');
        }
        return $this->render('articles/form.html.twig', [
           'form' => $form->createView(),
            'articles' => null,
        ]);
    }

    /**
     * @Route("/delete/{article}", name="delete_article")
     */
    public function delete(Articles $article)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($article);
        $em->flush();

        return $this->redirectToRoute('articles');
    }

    /**
     * @Route("/update/{article}", name="update_article")
     */
    public function update(Request $request, Articles $article)
    {
        $form = $this->createForm(ArticlesType::class, $article, [
            'action' => $this->generateUrl('update_article',[
                'article' => $article->getId()
            ]),
            'method' => 'POST',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $article = $form->getData();
            $article->setUpdatedAt(new \DateTime('now'));

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute('articles');
        }

        return $this->render('articles/form.html.twig', [
            'form' => $form->createView(),
            'articles' => $article,
        ]);
    }
}

blog/templates/articles/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticlesController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <div>
            {% if articles != null %}
                <a href="{{ path('single_article', {'article' : articles.id}) }}" class="btn btn-danger">Назад</a>
            {% else %}
                <a href="{{ path('articles') }}" class="btn btn-danger">Назад</a>
            {% endif %}
            {{ form_start(form) }}

            <div class="form-group">
                <label for="textarea">{{ form_label(form.title) }}</label>
                {{ form_widget(form.title, {'attr': {'class':'form-control'}}) }}
            </div>
            <div class="form-group">
                <label for="textarea">{{ form_label(form.author) }}</label>
                {{ form_widget(form.author, {'attr': {'class':'form-control'}}) }}
            </div>
            <div class="form-group">
                <label for="textarea">{{ form_label(form.content) }}</label>
                {{ form_widget(form.content, {'attr': {'class':'form-control'}}) }}
            </div>

            <button type="submit" class="btn btn-primary" >Опубликовать</button>

            {{ form_end(form) }}
        </div>

    </div>
{% endblock %}

blog/templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticlesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1 align="center">Articles List</h1>
    <div align="center">
        <a href="{{ path('create_article') }}">Создать запись</a>
    </div>

        {% for article in articles %}
            <div class="card text-center" style="margin-bottom: 20px">
                <div class="card-header">
                    {{ article.title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ article.author }}</h5>
                    <p class="card-text">{{ article.content|slice(0,255) }}</p>
                    <a href="{{ path('single_article', {'article': article.id}) }}" class="btn btn-primary">More</a>
                </div>
                <div class="card-footer text-muted">
                    Создано: {{ article.createdAt|date("F j Y h:i:s A") }}
                    {% if article.updatedAt != null %}
                        <br> Обновлено: {{ article.updatedAt|date("F j Y h:i:s A") }}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% if articles|length>4 %}
        <div align="center">
            <a href="{{ path('create_article') }}">Создать запись</a>
        </div>
    {% endif %}
</div>
{% endblock %}

blog/templates/articles/single.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ articles.title }}{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <a href="{{ path('articles') }}" class="btn btn-secondary">Назад</a>
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ articles.title }}</h5>
                <p class="card-text">{{ articles.content }}</p>
                {% set difference = date('now').diff(date(articles.createdAt)) %}
                {% set leftDays = difference %}
                <p class="card-text"><small class="text-muted">Создано {{ articles.createdAt|date("F j Y h:i:s A")}}</small></p>
                {% if articles.updatedAt!=null %}
                <p class="card-text"><small class="text-muted">Last updated {{ articles.updatedAt|date("F j Y h:i:s A")}}</small></p>
                {% endif %}
                <a href="{{ path('update_article', {'article':articles.id}) }}" class="btn btn-primary btn-md btn-block">Редактировать</a>

                <a href="{{ path('delete_article',{'article':articles.id}) }}" class="btn btn-primary btn-md btn-block">Удалить</a>
            </div>
        </div>

    <h4 >Комментарии: </h4>
    <a href="{{ path('create_comment', {'article': articles.id}) }}" class="btn btn-success" style="margin-bottom: 8px">Создать</a>
    {% for comment in comments %}
        <div class="card">
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ comment.author }}</p>
                    <p>{{ comment.content }}</p>
                    <footer class="blockquote-footer"><cite title="Source Title">{{ comment.createdAt|date() }}</cite></footer>
                </blockquote>
            </div>
        </div>

    {% endfor %}






    </div>


{% endblock %}